# Домашня робота №2

## 1 Пароль
Напишіть програму (функцію) для генерування випадкового пароля з такими обмеженнями:
- пароль складається з рівно $10$ символів
- пароль містить хоча б одну маленьку латинську літеру [a-z]
- пароль містить хоча б одну велику латинську літеру [A-Z]
- пароль містить хоча б одну цифру [0-9]
- пароль містить хоча б один спеціальний символ [~!@#$%^&*()-_+=\/{}[].,?<>:;]

In [2]:
# Місце для Вашого коду
import numpy as np
A=list();
for i in range(33,127):
  A.append(chr(i))
B=list();
for i in range(33,48):
  B.append(chr(i))
for i in range(91,96):
  B.append(chr(i))
for i in range(58,65):
  B.append(chr(i))
for i in range(123,127):
  B.append(chr(i))
C=list()
for i in range(48,58):
  C.append(chr(i))
  D=list()
for i in range(65,91):
  D.append(chr(i))
H=list()
for i in range(97,123):
  H.append(chr(i))
parol=list();
parol.append(np.random.choice(B))
parol.append(np.random.choice(C))
parol.append(np.random.choice(D))
parol.append(np.random.choice(H))
for i in range(4,10):
  parol.append(np.random.choice(A))
np.random.shuffle(parol)
print("Parol",parol)



Parol ['q', 's', '2', 't', 'D', 'i', 's', 'w', '|', 'C']


## 2 Герби в ряд
Реалізуйте функцію для обчислення емпіричної та теоретичної імовірностей випадіння $k$ гербів (HEADS) підряд у серії з $n$ підкидань чесної монетки. Підрахуйте відповідні ймовірності для таких параметрів:
- $k = 2, n = 10, 50, 100, 500, 1000, 5000, 10000$
- $k = 3, n = 10, 50, 100, 500, 1000, 5000, 10000$

**Зауваження.** Нехай $k = 2, n = 10$ та маємо таку послідовність результатів підкидання монети: $\{ H, T, H, H, H, H, T, T, H, T \}$. Тоді матимемо $3$ випадки випадіння двох гербів підряд та емпіричну ймовірність такої події $1/3$.

In [ ]:
# Місце для Вашого коду
import numpy as np

from itertools import combinations_with_replacement
def monetka(k,n,A=[0,1]):
  prb=0
  monet=np.random.choice(A,10)
  for i in range(1,len(monet)):
    if monet[i]==monet[i-1]:
      prb+=1
  print(monet)
  print("Empiric Probability(№2):",prb/((n//k - 1)*k+(n%k+1)),"for parameters n,k",n," ",k)
  choose_k=list(combinations_with_replacement(A,n))
  for i in choose_k:
    prb=0
    for j in range(1,len(i)):
      if i[j]==i[j-1]:
        prb+=1
  print("Probability(№2):", prb/(((n//k - 1)*k+(n%k+1))*len(choose_k)),"for parameters n,k",n," ",k)


  
monetka(2,10)  
monetka(2,50)
monetka(2,100)
monetka(2,500)  
monetka(2,1000)  
monetka(2,5000)  
monetka(2,10000)
monetka(3,10)  
monetka(3,50)
monetka(3,100)
monetka(3,500)  
monetka(3,1000)  
monetka(3,5000)  
monetka(3,10000)



[1 1 1 1 0 1 1 0 0 0]
Empiric Probability(№2): 0.6666666666666666 for parameters n,k 10   2
Probability(№2): 0.09090909090909091 for parameters n,k 10   2
[1 0 1 1 0 1 1 1 1 1]
Empiric Probability(№2): 0.10204081632653061 for parameters n,k 50   2
Probability(№2): 0.0196078431372549 for parameters n,k 50   2
[1 0 0 1 1 0 1 1 0 0]
Empiric Probability(№2): 0.04040404040404041 for parameters n,k 100   2
Probability(№2): 0.009900990099009901 for parameters n,k 100   2
[1 0 1 0 1 0 0 0 0 1]
Empiric Probability(№2): 0.006012024048096192 for parameters n,k 500   2
Probability(№2): 0.001996007984031936 for parameters n,k 500   2
[0 0 1 1 1 0 0 0 1 1]
Empiric Probability(№2): 0.006006006006006006 for parameters n,k 1000   2
Probability(№2): 0.000999000999000999 for parameters n,k 1000   2
[1 1 0 0 0 0 1 1 1 1]
Empiric Probability(№2): 0.0014002800560112022 for parameters n,k 5000   2
Probability(№2): 0.0001999600079984003 for parameters n,k 5000   2
[0 1 1 0 1 0 0 1 1 0]
Empiric Probability(№2)

## 3 Найбільше число
Реалізуйте функцію підрахунку точної (теоретичної) імовірності того, що максимальне число після $n$ кидків звичайного грального кубика дорівнює $x\_max$, для таких параметрів:
- $n = 3, x\_max = 6$
- $n = 2, x\_max = 3$
- $n = 3, x\_max = 5$

Тобто, якщо $X_i, i = 1, \ldots, n$, - число на $i$-му кидку кубика, а $X = \max\limits_{1 \leq i \leq n} X_i$, то потрібно знайти ймовірність $\textbf{P} \left( X = x\_max \right)$.

Підрахуйте також емпіричні ймовірності відповідних подій у випадку $10000$ симуляцій.

**Зауваження.** Якщо введені параметри не мають сенсу, то повертати $0$.
Тобто, якщо вводиться $x\_max < 1$ або $x\_max > 6$.

In [6]:
# Місце для Вашого коду
import numpy as np
from itertools import combinations_with_replacement

def exemprb(n,x_max,kub=[1,2,3,4,5,6]):
    if x_max<1:
        return 0
    if x_max>6:
        return 0
    prb=0
    choose_k = list(combinations_with_replacement(kub,n))
    for i in choose_k:
      if x_max==max(i):
        prb+=1
    print("Probability(№3):",prb/(len(choose_k)),"for parameters n,x_max",n," ",x_max)
  #eмпірична
    prb=0
    for i in range(10000):
      s=np.random.randint(1, 7, n)
      if x_max==max(s):
        prb+=1
    print("Empiric Probability(№3):",prb/((10000//n - 1)*n+(10000%n+1)),"for parameters n,x_max",n," ",x_max)
exemprb(3,6)
exemprb(2,3)
exemprb(3,5)


Probability(№3): 0.375 for parameters n,x_max 3   6
Empiric Probability(№3): 0.42058411682336466 for parameters n,x_max 3   6
Probability(№3): 0.14285714285714285 for parameters n,x_max 2   3
Empiric Probability(№3): 0.13751375137513752 for parameters n,x_max 2   3
Probability(№3): 0.26785714285714285 for parameters n,x_max 3   5
Empiric Probability(№3): 0.28965793158631725 for parameters n,x_max 3   5


## 4 Сума чисел
Реалізуйте функцію підрахунку точної (теоретичної) імовірності того, що сума чисел після $n$ кидків звичайного грального кубика дорівнює $s$, для таких параметрів:
- $n = 3, s = 13$
- $n = 2, s = 5$
- $n = 3, s = 7$

Тобто, якщо $X_i, i = 1, \ldots, n$, - число на $i$-му кидку кубика, а $X = \sum\limits_{i = 1}^{n} X_i$, то потрібно знайти ймовірність $\textbf{P} \left( X = s \right)$.

Підрахуйте також емпіричні ймовірності відповідних подій у випадку $10000$ симуляцій.

**Зауваження.** Якщо введені параметри не мають сенсу, то повертати $0$.
Наприклад, якщо при $n = 3$ вводиться $s < 3$ або $s > 18$.

In [7]:
# Місце для Вашого коду

import numpy as np
from itertools import combinations_with_replacement

def exemsum(n,sum,kub=[1,2,3,4,5,6]):
    if sum<n:
        return 0
    if sum>n*6:
        return 0
    prb=0
    choose_k = list(combinations_with_replacement(kub,n))
    for i in choose_k:
      sum1=0
      for j in range(len(i)):
        sum1+=i[j]
      if(sum1==sum):
        prb+=1;
    print("Probability(№4):",prb/(len(choose_k)),"for parameters n,sum",n," ",sum)
  #емпірична
    prb=0
    for m in range(10000):
      s=np.random.randint(1, 7, n)
      sum1=0
      for i in s:
        sum1+=i
      if(sum1==sum):
        prb+=1;

    print("Empiric Probability(№4):",prb/((10000//n - 1)*n+(10000%n+1)),"for parameters n,sum",n," ",sum)

exemsum(3,13)
exemsum(2,5)
exemsum(3,7)


Probability(№4): 0.08928571428571429 for parameters n,sum 3   13
Empiric Probability(№4): 0.09561912382476495 for parameters n,sum 3   13
Probability(№4): 0.09523809523809523 for parameters n,sum 2   5
Empiric Probability(№4): 0.10961096109610961 for parameters n,sum 2   5
Probability(№4): 0.07142857142857142 for parameters n,sum 3   7
Empiric Probability(№4): 0.07051410282056411 for parameters n,sum 3   7
